### ISSUE TITLE
Oracle design

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kcoin#208]
We need to come up with an oracle proposal that meets our requirements and can be built in the new few months.

**Comment by rgeraldes** [comment]
- Fetch price and volume (exchange).
- Exchanges reputation - user should be able to report faulty exchanges via UI and we should include a mechanism to temporarily disable certain exchanges based on the feedback provided.
- providing a price manually does not make much sense after including a lot of exchanges.

**Comment by yourheropaul** [comment]
I think the design probably done on this, so I'm closing.
