### ISSUE TITLE
[consensus] review timeouts (performance tests)

### ISSUE THREAD

**Issue by rgeraldes** [kowala-tech/kcoin#213]
### _Type_:
Request

### _What do you need?_:
We need to be sure that we provide valid timeouts based on the minimum hardware requirements.
Tendermint default values: https://github.com/tendermint/tendermint/blob/master/config/config.go#L441.

- e2e benchmarks on the target hardware

### _Priority_:
Medium

**Comment by acroca** [comment]
What would be the minimum hardware requirements?
At the moment the CI runs the e2e tests run in a docker-in-docker environment (`docker:dind`), which slows things up (at least on my local dev environment it's much slower). The CI itself is not very powerful (it's a t2.medium).

**Comment by acroca** [comment]
@rgeraldes do you mind closing this issue or unassigning me? Thanks
