### ISSUE TITLE
[containers] review package

### ISSUE THREAD

**Issue by rgeraldes** [kowala-tech/kcoin#216]
### _Type_:
Request

### _What do you need?_:
Do we need this package/do you want you use it? If not, let's remove it.
https://github.com/kowala-tech/kcoin/tree/dev/containers

### _Priority_:
Low

**Comment by acroca** [comment]
I didn't know about it. I'm not using that, I think it can be removed.

**Comment by rgeraldes** [comment]
Do we need to docker files in the root or is it possible to specify a different folder - it would be cool if we included them in a folder instead of having them in the root.

**Comment by acroca** [comment]
We don't need them there, I can probably move them to `release` maybe?

**Comment by rgeraldes** [comment]
release/containers sounds good
