### ISSUE TITLE
add token management address (mUSD contract)

### ISSUE THREAD

**Issue by heliorosa** [kowala-tech/kcoin#27]
Currently the mUSD contract uses a single address to manage ownership/delegation of tokens and mining. In order to reduce the exposure of the miners private key, an address needs to be added for mining purposes only any kUSD rewards should be paid to the token management address.

**Comment by yourheropaul** [comment]
We should probably separate out where the rewards are paid. It would be ideal if I could control tokens with address A, mine with address B and have the rewards paid to address C. That way I can keep my ownership private key in a vault somewhere, mine on AWS and get paid to an app on my phone.

To that end we need three things:

[x] A map of public addresses that own tokens (we have that)
[ ]  A mining delegation address for all token sets
[ ] A payment address for all token sets

**Comment by yourheropaul** [comment]
Token owners should be able to delegate their tokens to any number of miners at fixed rates of return. For example, owner A (who has 100 tokens) should be able to delegate 50 tokens to miner B for a 25% return and 25 tokens to miner C for a 50% return, while keeping the other tokens out of the mining pool.

**Comment by yourheropaul** [comment]
There is a complexity here: Is there a way for the receiving node to accept the tokens? If there isn't, then I could attach tokens to any node and they would do my mining for me.
