### ISSUE TITLE
[validator] Leave validation might not leave

### ISSUE THREAD

**Issue by jmatosp** [kowala-tech/kcoin#293]
### _Type_:
Issue

### _If it's an issue, how can we reproduce it?_:

When trying to leave an election if an error is returned from the contract we only log
We will still be in the election

`validator.go`

```
func (val *validator) leave() {
	err := val.election.Leave(val.walletAccount)
	if err != nil {
		log.Error("failed to leave the election", "err", err)
	}
}
```

### _Priority_:
Medium

**Comment by rgeraldes** [comment]
This is the expected behaviour - If the users fails to post the transaction, he should remain in the election.  
Closing this one for now - please open if necessary.
