### ISSUE TITLE
Make coin_id dynamic

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kcoin#321]
The current coin ID (see `accounts/hd.go`) is `60` (and there's a PR for `91927009`). This was intended to allow for a SLIP 44 ID for kUSD, but it will cause a problem if we want to create further currencies with the same codebase.

We need a way of making the coin ID in the default derivation paths dynamic.

**Comment by acroca** [comment]
This is sort of done, right?

**Comment by yourheropaul** [comment]
Yes
