### ISSUE TITLE
Figure out a way of making the network and chain IDs dynamic

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kcoin#329]
Since we want several networks (see #328) we need a way of making the network and chain IDs dynamic (currently they are partly in go code). 

The idea is that, during the CI process, we could compile, package and ship a docker image with the appropriate IDs.

This should be related to the currency and network (#358).

**Comment by yourheropaul** [comment]
Update: the only real purpose of this is to allow for `--currency` and `--testnet`  CLI flags, so it's probably not necessary to use `ldflags` I will update the title.

**Comment by yourheropaul** [comment]
Further note: this may already be implemented (at least partly) because `--testnet` seems to work.

**Comment by jmatosp** [comment]
I think we can close this @yourheropaul
