### ISSUE TITLE
[flags] Enable the default genesis for the TestnetFlag 

### ISSUE THREAD

**Issue by rgeraldes** [kowala-tech/kcoin#339]
### _Type_:
Issue

### _What happened? / What do you need?_:
We had to temporarily disable the TestnetFlag genesis because it was overriding the initial genesis and we must hardcoded the new genesis first. #278

### _Priority_:
Low

**Comment by acroca** [comment]
is this issue still relevant?

**Comment by yourheropaul** [comment]
No.
