### ISSUE TITLE
kcoin version output

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kcoin#351]
Currently, the output looks like this:

```
$ docker run --rm -it kowalatech/kusd:dev --testnet version
WARN [06-05|09:20:18] No coinbase set and no accounts found as default
INFO [06-05|09:20:18] Allocated cache and file handles         database=/root/.kcoin/kcoin/chaindata cache=16 handles=16
INFO [06-05|09:20:18] Writing custom genesis block
WARN [06-05|09:20:18] Error information
INFO [06-05|09:20:18] Successfully wrote genesis state
Kcoin
Version: 1.0.0-unstable
Git Commit: ae4a247461afdca9a1275d5b53eeb89b789e0423
Architecture: amd64
Protocol Versions: [1]
Network Id: 1
Go Version: go1.9.2
Operating System: linux
GOPATH=
GOROOT=/usr/local/go\
```

Which seems a bit weird. Ideally it  include:

- [x] The current version from git (either a tag or something to indicate it's unstable)
- [ ] The proper network ID
- [ ] The current chain ID
- [x] The proper protocol version (if it's not currently correct)
- [x] The compilation date, in any format

And it doesn't need:

- [x] The log output at the top
- [x] the GOPATH and GOROOT

It might or might not need:

- [ ] The data directory
- [ ] genesis checksum

**Comment by acroca** [comment]
Does it make sense to display network ID and chain ID? They depend of the argument you use, so running the `version` with or without `--testnet` will be different, which I find a bit weird.

**Comment by acroca** [comment]
Is this good enough?
```
$ docker run --rm kowalatech/kusd:test --testnet version
Kcoin
Version: 1.2.3-stable
Git Commit: e5dc1c0f52c07008ea0fb273a1b110e830867f06
BuildTime: 2018-06-27T09:55:48Z
Architecture: amd64
Protocol Versions: [1]
Network Id: 1
Go Version: go1.10.3
Operating System: linux
```
