### ISSUE TITLE
Embed genesis.json in the binaries

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kcoin#358]
Like geth, the various genesis.json files (for now just zygote testnet, but later main net and dev/master unstable networks) will need to be embedded inside the kcoin binary and used by default.

Note: The idea is that there will be multiple currencies (see #360), so it there's any way to future proof this, that would be idea. Otherwise we can come to it later.

The tasks are more or less this:

- [x] Create a `--currency` flag. There's currency only one currency, `kusd`, so this flag should be optional. When there are two or more currencies, it should be required.
- [x] Create a mapping of currency -> testnet genesis files. This is currently just kUSD's main net and testnet, but it should be extensible.
- [x] Set up a Makefile task to embed the genesis files in the binary
- [x] Alter the default genesis loading behaviour to load the proper genesis.json from binary storage unless the `--genesis` flag is explicitly specified.
- [ ] Ensure the Makefile task is run in CI so the binary always has the proper genesis config embedded in it.
- [ ] Make sure the faucet binary works in the same way. 
- [ ]  Remove all `--genesis` references in the kUSD and faucet Dockerfiles, and take the genesis.json files out of the images.

**Comment by jmatosp** [comment]
found an elegant solution for this, working on it

**Comment by JekaMas** [comment]
@jmatosp Are you talking about something like https://github.com/jteeuwen/go-bindata ? Just curious.

**Comment by jmatosp** [comment]
was a diff solution, finish yours, then we can go thru on the PR

**Comment by acroca** [comment]
This is done, right?
