### ISSUE TITLE
Support multiple currencies

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kcoin#360]
kUSD is the first currently, bu the goal is to support many different currencies (kEUR, kGBP,  kCDN, etc.). To accomplish this, we probably need a `--currency=kUSD` flag (with kUSD being the default for now) that sets up:

- [x]  The right genesis file (combined with `--testnet` flags)
- [x] Names of the currency (mostly in things like the console)
- [ ] Any oracle-related config
- [x] Data paths

**Comment by jgimeno** [comment]
The oracle is confirmed with ricardo that there is nothing to do for now on this.
