### ISSUE TITLE
Provide assets to the crypto exchange Exrates to get kUSD listed

### ISSUE THREAD

**Issue by johnreitano** [kowala-tech/kcoin#435]
We need to provide assets to the crypto exchange Exrates to get kUSD listed. It looks like they can get started by using our testnet.

Here is my summary of what they need:
• source code
• build instructions
• binary files
• block explorer
• wallet (web or desktop)
• testnet info
• faucet

For details of their requirements, see page 2 of the attached document, under "3. Ethereum fork coins".

[Technical Requirements.pdf](https://github.com/kowala-tech/kcoin/files/2138076/Technical.Requirements.pdf)

**Comment by yourheropaul** [comment]
Related to #508 and #473

**Comment by yourheropaul** [comment]
This needs:

- [ ] Some kind of wallet (Review #547)
- [ ] Assets as github releases 
- [ ] Documentation review

**Comment by yourheropaul** [comment]
Also:

- [ ] Add link to block explorer in netstats
- [ ] Add link to block explorer in testnet documentation
- [ ] Add link to block nerstats in testnet documentation

**Comment by yourheropaul** [comment]
Also:

- [ ] Add link to block explorer in netstats

**Comment by yourheropaul** [comment]
Downloads at https://docs.kowala.io/getting-started/download/

**Comment by johnreitano** [comment]
Would it be possible to add another page to the docs titled "Technical Information for Exchanges" which bundles all the requested info one page with some text + links to various resources?  This way we could just email out one URL to all the interested exchanges.  If so, here is a suggested outline:

TECHNICAL INFORMATION FOR EXCHANGES

• Overview

The code for kUSD and other kCoins was originally forked off of the Ethereum codebase so the RPC API, command line options, and smart contract interface are nearly identical to that of Ethereum's geth client.

• Overview of Testnet: https://zygote.kowala.tech/
• Source code: https://github.com/kowala-tech/kcoin
• Build Instructions: ???
• Download of binary client files: https://docs.kowala.tech/getting-started/download/ (should this be .tech or .io?)
• Network Stats (Testnet): https://zygote.kowala.tech/stats/
• Block explorer (Testnet): ???
• Web or Desktop Wallet (Testnet): ???
• Faucet (Testnet):  https://faucet.zygote.kowala.tech/

**Comment by yourheropaul** [comment]
The build instructions are pretty simple:

1. Make sure is Go is installed ([official instructions](https://golang.org/doc/install)).
2. Get the sourcecode from github. (`git clone git@github.com:kowala-tech/kcoin.git`).
3. In the directory where you put the source code, run `make`.

**Comment by yourheropaul** [comment]
As for the documentation URL, at the moment it has to be docs.kowala.io. We publish to the .io domain on every merge to the dev branch (so quite often) and to .tech on every release (much less frequent). We haven't made a release since adding the links, so they're only on the .io domain at the moment.

**Comment by johnreitano** [comment]
Ok, here is what I have for now:

kUSD TECHNICAL INFORMATION FOR EXCHANGES

• Overview of Testnet: https://zygote.kowala.tech/
• Source code: https://github.com/kowala-tech/kcoin
• How to build: The client source code has no dependencies, and it will set up its own build environment. To build, follow these 2 steps: Install Go (see https://golang.org/doc/install); 2. Run: `git clone git@github.com:kowala-tech/kcoin.git; cd kcoin; make`
• Download of binary client files: https://docs.kowala.io/getting-started/download/
• Network Stats (Testnet): https://zygote.kowala.tech/stats/
• Block explorer (Testnet): https://explorer.zygote.kowala.tech/home
• Web or Desktop Wallet (Testnet): https://wallet.zygote.kowala.tech/
• Faucet (Testnet): https://faucet.zygote.kowala.tech/
• API Info: The code for kUSD and other kCoins was originally forked off of the Ethereum codebase so the RPC API and smart contract interface are identical to those of Ethereum's Go client.  See https://github.com/ethereum/go-ethereum
