### ISSUE TITLE
Set up a block explorer

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kcoin#451]
We need a block explorer so that certain exchanges will consider listing kUSD (see #435).

There are several options, and we'll need to research the best one for our needs. Whatever the solution, it must:

- [ ] be open source, and our fork should live in the mono-repo
- [ ] Have kowala/kusd branding (the pink-purple one for now)
- [ ] produce a Docker image for easy deployment

**Comment by jgimeno** [comment]
https://github.com/ethereumproject/explorer check this one too

@jmatosp so you take this task? :D

**Comment by jmatosp** [comment]
Yeah, could do this one.

What would be the minimal functionality?

Block view
Transactions view
Validators state?
