### ISSUE TITLE
[CI] include file generation (go generate) during the build

### ISSUE THREAD

**Issue by rgeraldes** [kowala-tech/kcoin#467]
### _Type_:
Issue

### _What happened?_:
The file generation was failing but it's not visible during the build since the codebase relies on the available generated files which were created on previous snapshots of the codebase that did not contain errors. We must include file generation in the build process to identify those situations and to make sure that we are using the latest version.

### _Affected servers or services_:
Contract bindings

### _Priority_:
High

**Comment by jgimeno** [comment]
@rgeraldes is this already done? I see on the  make bindings:

```# FILES is the list of binding files that would be created when generating the bindings
FILES=$(shell egrep -ir "go:generate" client/contracts/bindings | grep abigen | sed -E 's/^client\/contracts\/bindings\/(.*)\/.*\.go.*-out\ \.?\/?(.*)/client\/contracts\/bindings\/\1\/\2/' )
$(FILES):
	$(MAKE) -j 5 stringer go-bindata gencodec client/build/bin/abigen client/contracts/truffle/node_modules
	go generate ./client/contracts/bindings/...
bindings: | $(FILES)```
