### ISSUE TITLE
Change location of go-bindings and how they are generating

### ISSUE THREAD

**Issue by JuliusBrain** [kowala-tech/kcoin#472]
### _Type_:
Issue

### _What happened? / What do you need?_:
Move all go code from /client/contracts to /client/bindings
### _If it's an issue, how can we reproduce it?_:
After adding truffle generation of go-bindings do not work
### _Priority_:
Medium

  * High = We should stop anything we are doing and do this.
If you're writing this calmly, you should probably choose another option.
If it's really that urgent, please make sure we read this.
  * Medium = It's important that we do this within a few days.
  * Low = We will consider this on our next sprint planning.

(Please be aware that your priority may not match ours, we'll use this as guidance only).

**Comment by yourheropaul** [comment]
We also need to make sure that the bindings are re-regenerated (or rather, re-`go generate`d) on build. This could be as simple as adding a `go generate ...` command to the Makefile task.

**Comment by JuliusBrain** [comment]
I will do that in the next commit
