### ISSUE TITLE
[explorer] Styling

### ISSUE THREAD

**Issue by jmatosp** [kowala-tech/kcoin#479]
### _Type_:
Issue
### _What happened? / What do you need?_:

"
It's quite hard to read some of the text (for example 0 txns by in this screenshot.

The About and Follow Us On sections seem to be incomplete. Maybe just delete them?

The loading spinner (the 3 green hexagons) looks really dwanky. It should probably just be white, and less pixelated. I can help with that if required.
"

**Comment by yourheropaul** [comment]
I'm going to close this for now
