### ISSUE TITLE
Consolidate new website branding

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kcoin#501]
The new website is blue rather than pink-and-purple. We need to make sure that all the web parts of the system (netstats, block explorer, docs) have something close the same branding. 

The easiest way to achieve this is to make a single shared bit of SASS/CSS for all components.

Estimate: 24h

**Comment by adamking** [comment]
https://github.com/kowala-tech/kowala-styles

**Comment by adamking** [comment]
I've moved the testnet landing page to the kowala.tech repo.

**Comment by yourheropaul** [comment]
The complete list of things that need to be on-brand is:

- Netstats
- Block explorer
- Wallet app
- Wallet-tools app (myetherwallet)
- Docs site
- Faucet
- Main website

For all but the main website, we need multiple presentation modes somehow: one for main net, another for testnet (`zygote`) and eventually one for an internal testnet (probably called `dev`).

**Comment by yourheropaul** [comment]
So I just setup cdn.kowala.io for internal and dev styles. I don't really know what the differences will be between dev and prod (probably just logos) but I think it's worth distinguishing between them.

In order to accomplish that on the wallet-tools app, which need for Ledger, I've created some build-time config: https://github.com/kowala-tech/kcoin/pull/595/commits/a499e3cefbce6d3c2443ca6442cc1965a2066a13. What that essentially means is that the dev docker image pulls its assets from cdn.kowala.io, and the prod version (which is the default) pulls them from cdn.kowala.tech. I guess all the applications will need something similar.

**Comment by adamking** [comment]
Everything except the faucet have been restyled in the PRs above. This is just a start as not everything works with multiple presentation modes.
