### ISSUE TITLE
Validator has been dropped as a peer

### ISSUE THREAD

**Issue by JekaMas** [kowala-tech/kcoin#522]
### _Type_:
Issue

### _What happened? / What do you need?_:
From time to time e2e tests fail because of validator node is dropped as a peer.
Logs - https://s3.amazonaws.com/kcoin-e2e/logs/1408/joining_network_as_a_validator-010-validator-under-test-tXUp.log

### _If it's an issue, how can we reproduce it?_:
Run e2e tests until them fail.

### _Priority_:
Medium

**Comment by acroca** [comment]
The piece that seems relevant from that logs:
```
WARN [07-12|09:51:20.014] Synchronisation failed, dropping peer    peer=55d8e8011dd6186a err="action from bad peer ignored"
DEBUG[07-12|09:51:20.014] Removing Kowala peer                     peer=55d8e8011dd6186a
TRACE[07-12|09:51:20.014] Unregistering sync peer                  peer=55d8e8011dd6186a
DEBUG[07-12|09:51:20.014] Trie cache stats after commit            misses=0 unloads=0
DEBUG[07-12|09:51:20.014] Kowala message handling failed           id=55d8e8011dd6186a conn=inbound err=EOF
TRACE[07-12|09:51:20.014] Propagated block                         hash=a1d52d…7dc6d3 recipients=0 duration=2.076ms
DEBUG[07-12|09:51:20.014] Removing p2p peer                        id=55d8e8011dd6186a conn=inbound duration=1.031s             peers=0 req=false err="useless peer"
```

Also, the logs for the genesis validator, to see if it sent something wrong: https://s3.amazonaws.com/kcoin-e2e/logs/1408/joining_network_as_a_validator-010-genesis-validator-tXUp.log
