### ISSUE TITLE
[CI] We need to also build docker images on PRs

### ISSUE THREAD

**Issue by jmatosp** [kowala-tech/kcoin#523]
### _Type_:

Issue

### _If it's an issue, how can we reproduce it?_:

PR's don't build docker images, so when we merge this step could fail.

We should run this step to make sure passes 

### _Priority_:
High

**Comment by acroca** [comment]
We build most of them in the e2e step anyway to use them during the tests.

**Comment by jmatosp** [comment]
Is there a way to re use the build boxes for testing?
