### ISSUE TITLE
Validator didn't join the network

### ISSUE THREAD

**Issue by acroca** [kowala-tech/kcoin#536]
While running the e2e I get randomly this error:
```
  Scenario: Start validator # features/validator.feature:11
    Given I have the following accounts: # features/validator.feature:6
      Error: timeout error: node is synchronised
```

Here the logs: [logs.zip](https://github.com/kowala-tech/kcoin/files/2192366/logs.zip)

Apparently the new validator didn't join the network.
/cc @JekaMas

**Comment by JekaMas** [comment]
I've run a scenario `Re-Start mining` for 40 times and got only https://github.com/kowala-tech/kcoin/issues/607 and https://github.com/kowala-tech/kcoin/issues/519

So this issue is no more reproducible and seems fixed.
