### ISSUE TITLE
Add all generated files to the repo

### ISSUE THREAD

**Issue by acroca** [kowala-tech/kcoin#539]
We recently decided to gitignore the generated binding files.
I think we should have all generated content in the repo available for all of us whenever we pull the code.

The reason to add it to gitignore is because the generated files tend to get outdated, and having outdated files is worse than forcing it to be generated every time.

To better fix the issue I propose to add a task in the CI to check all generated files are up to date. That can be easily done doing a `go generate ./...` and making sure the `git diff` is empty.

What do you guys think?

/cc @kowala-tech/core-developers

**Comment by rgeraldes** [comment]
https://scene-si.org/2018/07/24/writing-great-go-code/ includes a section on generated files.

**Comment by acroca** [comment]
I think this is already done
