### ISSUE TITLE
Prepare a client that updates itself

### ISSUE THREAD

**Issue by acroca** [kowala-tech/kcoin#603]
Figure out a way to make the `kcoin` binary update itself when there's a new version.

This feature has to be optional so users can opt out, but enabled by default.

/cc @yourheropaul

**Comment by acroca** [comment]
Consider using https://github.com/jpillora/overseer, seems to do what we need.

**Comment by jmatosp** [comment]
Im working on this

**Comment by JekaMas** [comment]
Is it safe? Is there any chance that malicious actor can replace binaries?
@acroca @jmatosp

**Comment by jmatosp** [comment]
Very good point. 

A "mad" in middle attack would replace with it's own binary, but to be effective you will need A LOT of binaries to be replaced.

I do have concern on terminating the binary, it's a daemon doing stuff (validating, transferring, syncing, etc.)

**Comment by JekaMas** [comment]
All deamon stuff should works fine.
It'd be great if we can sign binaries and update only correctly signed binaries.

It seems to me that this feature can update binary even if it is a hard fork. Shall we ask a user about such updates?

* it's a kind of centralization to have such featute...

**Comment by jmatosp** [comment]
Yes, we the self update is optional.
Agree with the signed binary

Don't agree with centralisation. Paul raised same concerns, but don't think is a centralisation issue. It's optional and a way the ensure the binary is coming from the community (public github)

**Comment by JekaMas** [comment]
An optional feature and signed binaries looks good for me.

How we're going to work with soft and hard forks? A user should approve each protocol change or auto update shouldn't work with protocol changes.

**Comment by yourheropaul** [comment]
I've updated #377  with some restrictions.
