### ISSUE TITLE
Can't connect to testnet without using Docker image

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kcoin#683]
I get a bunch of `bad peer` error messages,

**Comment by yourheropaul** [comment]
I _can_ connect by passing `--nat none`.  For example, with `client/build/bin/kcoin --dev --nat none console`.

**Comment by yourheropaul** [comment]
Maybe the default should be `--nat none`? This will need to be manually tested

**Comment by jgimeno** [comment]
Looks solved
