### ISSUE TITLE
kcoin gives Fatal Error

### ISSUE THREAD

**Issue by johnreitano** [kowala-tech/kcoin#734]
### _Type_:
Issue

### _What happened? / What do you need?_:
When client Exrates builds from source and runs `kcoin` they get this error:
`Fatal: Error starting protocol stack: there isn't an address for the provided chain ID`
Adam was able to duplicate this error.

He got this same problem when running the binary.

### _If it's a request, what do you need it for?_:
To allow our first exchange, Exrates, to integrate and list kUSD.

### _If it's an issue, how can we reproduce it?_:
Build from source and run kcoin or download binary and run kcoin.

### _Priority_:
High

  * High = We should stop anything we are doing and do this.
If you're writing this calmly, you should probably choose another option.
If it's really that urgent, please make sure we read this.
  * Medium = It's important that we do this within a few days.
  * Low = We will consider this on our next sprint planning.

(Please be aware that your priority may not match ours, we'll use this as guidance only).

**Comment by yourheropaul** [comment]
This seems like an easily resolvable issue.
