### ISSUE TITLE
compiled kcoin client doesn't automatically sync

### ISSUE THREAD

**Issue by johnreitano** [kowala-tech/kcoin#766]
### _Type_: 
Issue

### _What happened? / What do you need?_:
When I start the client console, wait 5 minutes and then enter admin.peers, I get back an empty set.

### _If it's a request, what do you need it for?_:
To allow people and exchanges to connect to our network.

### _If it's an issue, how can we reproduce it?_:
Enter `kcoin console`.
Wait 5 minutes.
Enter `admin.peers`

### _Priority_:
High

**Comment by jgimeno** [comment]
@johnreitano can you try to remove the data folder, and do a "kcoin init" and later try it again?

**Comment by johnreitano** [comment]
That worked for me, but not for Adam. We're both using the Mac client (2.0.0-stable). What is a good way to debug this?

**Comment by adamking** [comment]
I was able to fix the peer problem with the flag `--nat none`. After peers are discovered, syncing continues normally without the flag set.
