### ISSUE TITLE
Crash/bad error message when attempting to mine

### ISSUE THREAD

**Issue by adamking** [kowala-tech/kcoin#786]
### _Type_:
Issue

### _What happened? / What do you need?_:
I attempted to start mining and the console returned an error but the message seems like a crash.

### _If it's an issue, how can we reproduce it?_:
Start with no mTokens and run:

> validator.start(web3.toWei(1000000,“kcoin”))
(anonymous): Line 1:36 Unexpected token ILLEGAL (and 4 more errors)

### _Priority_:
Low

  * High = We should stop anything we are doing and do this.
If you're writing this calmly, you should probably choose another option.
If it's really that urgent, please make sure we read this.
  * Medium = It's important that we do this within a few days.
  * Low = We will consider this on our next sprint planning.

(Please be aware that your priority may not match ours, we'll use this as guidance only).

**Comment by rgeraldes** [comment]
`validator.start(web3.toWei(n, 'ether'))`

**Comment by adamking** [comment]
“ether” gave @johnreitano an error, and he needed to replace it with "kcoin". Nevertheless, the error message is confusing.

**Comment by rgeraldes** [comment]
In the meantime, try replacing the toWei with eighteen zeros.
`validator.start(1000000000000000000000000)`
This command is working in the e2e tests.
